# -*- coding: utf-8 -*-
"""Cópia de liveCodingAula8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKYaUeAJCdVMR2jCrEeXzClWYwK821mn
"""

#instalando o
!pip install streamlit

import streamlit as st

st.write('vamos aprender juntas streamlit')

import streamlit as st
st.write('sou servidora publica')





